# Generated by Django 4.2 on 2023-12-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoffeeShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=1000)),
                ("latitude", models.CharField(blank=True, max_length=25, null=True)),
                ("longitude", models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
